export const PERMISSION_LABEL_KEY: Record<string, string> = {
  // calendar
  "calendar.view.own": "permission.calendar.view.own",
  "calendar.view.office": "permission.calendar.view.office",
  "calendar.view.organization": "permission.calendar.view.organization",
  "calendar.create.own": "permission.calendar.create.own",
  "calendar.create.office": "permission.calendar.create.office",
  "calendar.edit.own": "permission.calendar.edit.own",
  "calendar.edit.office": "permission.calendar.edit.office",
  "calendar.edit.organization": "permission.calendar.edit.organization",
  "calendar.delete.own": "permission.calendar.delete.own",
  "calendar.delete.office": "permission.calendar.delete.office",
  "calendar.delete.organization": "permission.calendar.delete.organization",
  "calendar.integrations.view.office": "permission.calendar.integrations.view.office",
  "calendar.integrations.manage.office": "permission.calendar.integrations.manage.office",

  // offers
  "offers.view.own": "permission.offers.view.own",
  "offers.view.office": "permission.offers.view.office",
  "offers.view.organization": "permission.offers.view.organization",
  "offers.create.office": "permission.offers.create.office",
  "offers.create.organization": "permission.offers.create.organization",
  "offers.edit.own": "permission.offers.edit.own",
  "offers.edit.office": "permission.offers.edit.office",
  "offers.edit.organization": "permission.offers.edit.organization",
  "offers.delete.office": "permission.offers.delete.office",
  "offers.delete.organization": "permission.offers.delete.organization",
  "offers.archive.office": "permission.offers.archive.office",
  "offers.publish.office": "permission.offers.publish.office",
  "offers.export.office": "permission.offers.export.office",
  "offers.images.view.office": "permission.offers.images.view.office",
  "offers.images.manage.office": "permission.offers.images.manage.office",
  "offers.notes.view.office": "permission.offers.notes.view.office",
  "offers.notes.manage.office": "permission.offers.notes.manage.office",

  // clients
  "clients.view.own": "permission.clients.view.own",
  "clients.view.office": "permission.clients.view.office",
  "clients.view.organization": "permission.clients.view.organization",
  "clients.view_sensitive.office": "permission.clients.view_sensitive.office",
  "clients.create.office": "permission.clients.create.office",
  "clients.edit.own": "permission.clients.edit.own",
  "clients.edit.office": "permission.clients.edit.office",
  "clients.delete.office": "permission.clients.delete.office",
  "clients.export.office": "permission.clients.export.office",
  "clients.contacts.view.office": "permission.clients.contacts.view.office",
  "clients.contacts.manage.office": "permission.clients.contacts.manage.office",
  "clients.addresses.view.office": "permission.clients.addresses.view.office",
  "clients.addresses.manage.office": "permission.clients.addresses.manage.office",
  "clients.consents.view.office": "permission.clients.consents.view.office",
  "clients.consents.manage.office": "permission.clients.consents.manage.office",

  // team
  "team.view.office": "permission.team.view.office",
  "team.view.organization": "permission.team.view.organization",
  "team.invite.office": "permission.team.invite.office",
  "team.edit_membership.office": "permission.team.edit_membership.office",
  "team.manage_roles.office": "permission.team.manage_roles.office",
  "team.manage_permissions.office": "permission.team.manage_permissions.office",
  "team.manage_profiles.office": "permission.team.manage_profiles.office",
  "team.deactivate.office": "permission.team.deactivate.office",

  // reports
  "reports.view.own": "permission.reports.view.own",
  "reports.view.office": "permission.reports.view.office",
  "reports.view.organization": "permission.reports.view.organization",
  "reports.export.office": "permission.reports.export.office",
  "reports.export.organization": "permission.reports.export.organization",

  // files
  "files.view.office": "permission.files.view.office",
  "files.upload.office": "permission.files.upload.office",
  "files.delete.office": "permission.files.delete.office",
  "files.export.office": "permission.files.export.office",

  // external_listings
  "external_listings.view.office": "permission.external_listings.view.office",
  "external_listings.view.organization": "permission.external_listings.view.organization",
  "external_listings.import.office": "permission.external_listings.import.office",
  "external_listings.assign.office": "permission.external_listings.assign.office",
  "external_listings.archive.office": "permission.external_listings.archive.office",
  "external_listings.enrich.office": "permission.external_listings.enrich.office",
  "external_listings.run_backfill.office": "permission.external_listings.run_backfill.office",
  "external_listings.run_backfill.global": "permission.external_listings.run_backfill.global",
};

export const PERMISSION_CATEGORY_KEY: Record<string, string> = {
  calendar: "permissionCategory.calendar",
  offers: "permissionCategory.offers",
  clients: "permissionCategory.clients",
  team: "permissionCategory.team",
  reports: "permissionCategory.reports",
  files: "permissionCategory.files",
  external_listings: "permissionCategory.external_listings",
};